# Generated by Django 4.2.5 on 2023-10-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=105)),
                ('purpose_of_visit', models.TextField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(choices=[('vip guest', 'Vip Guest'), ('auditor', 'Auditor'), ('inspection institutions', 'Inspection Institutions')], default='Vip Guest', max_length=23)),
                ('company_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorSecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_kpp', models.BooleanField(default=False)),
                ('access_card_to_kaba', models.BooleanField(default=False)),
                ('health_safety_training', models.BooleanField(default=False)),
                ('internet_accesses', models.BooleanField(default=False)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSafetyNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_helmet', models.BooleanField(default=False)),
                ('needs_vest', models.BooleanField(default=False)),
                ('needs_shoes', models.BooleanField(default=False)),
                ('size_shoes', models.CharField(blank=True, max_length=5, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_invoice', models.BooleanField(default=False)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_airport', models.DateTimeField(blank=True, null=True)),
                ('airport_to_wab', models.DateTimeField(blank=True, null=True)),
                ('airport_to_hotel', models.DateTimeField(blank=True, null=True)),
                ('hotel_to_wab', models.DateTimeField(blank=True, null=True)),
                ('wab_to_hotel', models.DateTimeField(blank=True, null=True)),
                ('own_transport', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('parking_choice', models.CharField(blank=True, choices=[('outside', 'Outside'), ('inside', 'Inside')], max_length=7, null=True)),
                ('wab_to_airport', models.DateTimeField(blank=True, null=True)),
                ('hotel_to_airport', models.DateTimeField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.BooleanField(default=False)),
                ('restaurant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_people', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('others', models.BooleanField(default=False)),
                ('others_thinks', models.TextField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='OutOfOfficeMeetingPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('transport', models.BooleanField(default=False)),
                ('numbers_of_people', models.IntegerField(blank=True, null=True)),
                ('transport_choice', models.CharField(blank=True, choices=[('car', 'Car'), ('bus', 'Bus'), ('company_car', 'Company car')], max_length=11, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='OtherRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('others', models.BooleanField(default=False)),
                ('others_thinks', models.TextField(blank=True, max_length=200, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('coffe', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('carbonated_drinks', models.BooleanField(default=False)),
                ('cookies', models.BooleanField(default=False)),
                ('beamer', models.BooleanField(default=False)),
                ('flipchart', models.BooleanField(default=False)),
                ('stickers', models.BooleanField(default=False)),
                ('room_others', models.BooleanField(default=False)),
                ('others_description', models.TextField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_menu_to_requester', models.BooleanField(default=False)),
                ('choose_menu_for_guest', models.BooleanField(default=False)),
                ('free_choice_for_company', models.BooleanField(default=False)),
                ('catering', models.BooleanField(default=False)),
                ('own_choice_menu', models.BooleanField(default=False)),
                ('own_free_choice', models.BooleanField(default=False)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_visitor', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
    ]
