# Generated by Django 5.0.3 on 2024-03-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=105)),
                ('purpose_of_visit', models.TextField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(choices=[('vip guest', 'Vip Guest'), ('auditor', 'Auditor'), ('inspection institutions', 'Inspection Institutions')], default='Vip Guest', max_length=23)),
                ('company_name', models.CharField(max_length=50)),
                ('day_of_arrival', models.DateField()),
                ('day_of_departure', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_people', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('others', models.BooleanField(default=False)),
                ('others_thinks', models.TextField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='OtherRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('others_thinks', models.TextField(blank=True, max_length=200, null=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_requirements', to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('coffe', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('carbonated_drinks', models.BooleanField(default=False)),
                ('cookies', models.BooleanField(default=False)),
                ('beamer', models.BooleanField(default=False)),
                ('flipchart', models.BooleanField(default=False)),
                ('stickers', models.BooleanField(default=False)),
                ('room_others', models.BooleanField(default=False)),
                ('others_description', models.TextField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_invoice', models.BooleanField(default=False)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSafetyNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_helmet', models.BooleanField(default=False)),
                ('needs_vest', models.BooleanField(default=False)),
                ('needs_shoes', models.BooleanField(default=False)),
                ('size_shoes', models.IntegerField(blank=True, null=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_needs', to='visitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_card_to_kaba', models.BooleanField(default=False)),
                ('health_safety_training', models.BooleanField(default=False)),
                ('internet_accesses', models.BooleanField(default=False)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_info', to='visitor.visitor')),
            ],
        ),
    ]
