# Generated by Django 4.2.11 on 2024-04-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_outofofficemeetingplanner_visitoraccommodation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outofofficemeetingplanner',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='visitorsafetyneeds',
            name='size_shoes',
        ),
    ]
