# Generated by Django 4.2.11 on 2024-04-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_remove_outofofficemeetingplanner_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsafetyneeds',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='VisitorAccommodation',
        ),
        migrations.DeleteModel(
            name='VisitorSafetyNeeds',
        ),
    ]
